module.exports = {
    UserSchema: require("./UserSchema"),
    CartSchema: require("./CartSchema"),
    UserCourseSchema: require("./UserCourseSchema"),
    CourseWatchHistorySchema: require("./CourseWatchHistorySchema"),
    UserMobileActivitySchema: require("./UserMobileActivitySchema"),
    UserLoginHistorySchema: require("./UserLoginHistorySchema"),
    NotesSchema: require("./NotesSchema"),
    QuizResultSchema: require("./QuizResultSchem"),
    PersonalizedQuizSchema: require("./PersonalizedQuizSchema"),
    SmsLogSchema: require("./SmsLogSchema"),
    ConjobLogSchema: require("./ConjobLogSchema"),
    ApiCallsSchema: require("./ApiCallsSchema"),
    InvoiceSchema: require("./InvoiceSchema"),
    PaymentWebhookSchema: require("./PaymentWebhookSchema"),
    PaymentLogsSchema: require("./PaymentLogsSchema"),
    EmailLogsSchema: require("./EmailLogs"),
    UserActivitySchema: require("./UserActivitySchema"),
    FeedbackSchema: require("./FeedbackSchema"),
    ContactUsSchema: require("./ContactUsSchema"),
    PaymentHistorySchema: require("./PaymentHistorySchema"),
    UserEarningSchema: require("./UserEarningSchema"),
}
