let userRoutes = require("./userApi")
let cartRoutes = require("./cartApi")
let userCourseRoutes = require("./userCourseApi")
let courseWatchHistoryRoutes = require("./courseWatchHistoryApi")
let userMobileActivityRoutes = require("./userMobileActivityApi")
let notesRoutes = require("./notesApi")
let quizResultRoutes = require("./quizResultApi")
let personalizedQuizRoutes = require("./personalizedQuizApi")
let userEventsRoutes = require("./userEvents")
let paymentWebhookRoutes = require("./webhooks/paymentWebhook")
let notificationWehhookRoutes = require("./webhooks/notificationWehhook")
let checkSubscriptionRoutes = require("./cronjobs/checkSubscription")
let userActivityRoutes = require("./userActivityApi")
let feedbackRoutes = require("./feedbackApi")
let ContactUsApi = require("./ContactUsApi")

module.exports = (app) => {
    userRoutes(app)
    cartRoutes(app)
    userCourseRoutes(app)
    courseWatchHistoryRoutes(app)
    userMobileActivityRoutes(app)
    notesRoutes(app)
    quizResultRoutes(app)
    personalizedQuizRoutes(app)
    userEventsRoutes(app)
    paymentWebhookRoutes(app)
    checkSubscriptionRoutes(app)
    notificationWehhookRoutes(app)
    userActivityRoutes(app)
    feedbackRoutes(app)
    ContactUsApi(app)
}
