module.exports = {
    SUCCESS_RESPONSE: 200,
    ERROR_RESPONSE: 400,
    DATABASE_ERROR_RESPONSE: 500,
    CONFLICT_RESPONSE: 409,
    OTP_EXPIRE_MINUTE: 1,
    EXCEPTION_ERROR_CODE:410,

    //send mail address configuration
    EMAIL_TEMPLATE_MAIL_ID: "info@virtualafsar.com",
    // EMAIL_TEMPLATE_MOBILE_NO: "+91 91042 91082",
    EMAIL_TEMPLATE_MOBILE_NO: "+91 848-79-848-59",

    EMAIL_TEMPLATE_ADDRESS: "803, 8th Floor, Runway Heights,Ayodhya Chawk, 150 ft. Ring Road,Rajkot, Gujarat 360006",

    EMAIL_TEMPLATE_FACEBOOK_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/facebooks.png",
    EMAIL_TEMPLATE_INSTAGRAM_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/instagrams.png",
    EMAIL_TEMPLATE_LINKEDIN_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/linkedin.png",
    EMAIL_TEMPLATE_TWITTER_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/twitter.png",
    EMAIL_TEMPLATE_YOUTUBE_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/youtube.png",

    EMAIL_TEMPLATE_BLUETODO_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/blueTodo.png",
    EMAIL_TEMPLATE_BOYMOBILE_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/BoyMobile.png",
    EMAIL_TEMPLATE_MOBILECAR_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/mobilecar.png",
    EMAIL_TEMPLATE_FB_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/fb.png",
    EMAIL_TEMPLATE_HERO1_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/hero1.png",
    EMAIL_TEMPLATE_HERO2_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/hero2.png",
    EMAIL_TEMPLATE_HERO3_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/hero3.png",
    EMAIL_TEMPLATE_HERO4_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/hero4.png",
    EMAIL_TEMPLATE_IN_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/in.png",
    EMAIL_TEMPLATE_INSTA_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/insta.png",
    EMAIL_TEMPLATE_LOGOGIF_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/logoGif.gif",
    EMAIL_TEMPLATE_MAIL_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/mail.png",
    EMAIL_TEMPLATE_PHONE_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/phone.png",
    EMAIL_TEMPLATE_VALOGO_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/VAlogo.png",
    EMAIL_TEMPLATE_WEB_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/web.png",
    EMAIL_TEMPLATE_YELLOWTODO_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yellowTodo.png",
    EMAIL_TEMPLATE_YFB_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yfb.png",
    EMAIL_TEMPLATE_YIN_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yin.png",
    EMAIL_TEMPLATE_YINSTA_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yinsta.png",
    EMAIL_TEMPLATE_YMAIL_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/ymail.png",
    EMAIL_TEMPLATE_YPHONE_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yphone.png",
    EMAIL_TEMPLATE_YT_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yt.png",
    EMAIL_TEMPLATE_YTWITTER_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/ytwitter.png",
    EMAIL_TEMPLATE_YWEB_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yweb.png",
    EMAIL_TEMPLATE_YYT_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/yyt.png",
    EMAIL_TEMPLATE_HINDITXT_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/hindiTxt.png",
    EMAIL_TEMPLATE_WHITEBG_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/whiteBg.png",
    EMAIL_TEMPLATE_COURSEUP_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/csUp.png",
    EMAIL_TEMPLATE_COURSEDOWN_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/csDown.png",
    EMAIL_TEMPLATE_WWCHERO_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/wwcHero.png",
    
    
    EMAIL_TEMPLATE_FACEBOOK_LINK: "https://www.facebook.com/profile.php?id=100095410212980&mibextid=ZbWKwL",
    EMAIL_TEMPLATE_INSTAGRAM_LINK: "https://instagram.com/virtualafsar?igshid=MzRlODBiNWFlZA==",
    EMAIL_TEMPLATE_LINKEDIN_LINK: "https://www.linkedin.com/in/virtual-afsar-b74a00287/",
    EMAIL_TEMPLATE_TWITTER_LINK: "https://twitter.com/virtualafsar",
    EMAIL_TEMPLATE_YOUTUBE_LINK: "https://www.youtube.com/@VirtualAfsar",
    
    EMAIL_TEMPLATE_LOCK_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/lock.png",
    EMAIL_TEMPLATE_LOGO_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/vv_logo.png",
    EMAIL_TEMPLATE_VV_LOGO_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/vv_logo.png",
    EMAIL_TEMPLATE_VV_LOGO_BLACK_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/vv_logo.png",
    EMAIL_TEMPLATE_VV_FOOTER_LOGO_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/footer_logo.png",
    EMAIL_TEMPLATE_PAID_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/paid_svg.png",
    EMAIL_TEMPLATE_UNPAID_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/unpaid_svg.png",
    EMAIL_UNSUBSCRIBE_URL: process.env.IMAGE_URL + "/api/client/unsubscribe",
    EMAIL_COURSE_URL: process.env.BASE_URL + "coursePage/",
    EMAIL_BASE_URL: "https://virtualafsar.com/",

    EMAIL_TEMPLATE_APP_STORE_URL: "https://apps.apple.com/in/app/virtual-afsar/id6459960071",
    EMAIL_TEMPLATE_PLAY_STORE_URL: "https://play.google.com/store/apps/details?id=com.tjcg.virtualvidhyapith",
    EMAIL_TEMPLATE_APP_STORE_ICON_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/appstore.png",
    EMAIL_TEMPLATE_PLAY_STORE_ICON_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/playstore.png",
    STUDENT_LOGIN_URL: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/email_assets/twitter.png",

    INVOICE_STATUS_PAID: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/paid.png",
    INVOICE_STATUS_FAILED: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/failed.png",
    INVOICE_STATUS_REFUNDED: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/refunded.png",
    INVOICE_STATUS_UNPAID: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/unpaid.png",
    INVOICE_STATUS_UNPAID: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/unpaid.png",
    INVOICE_HEADER_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/HeaderInvoice.png",
    INVOICE_FOOTER_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/InvoiceFooter.png",

    INVOICE_LOCATION_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/location.png",
    INVOICE_MAIL_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/mail.png",
    INVOICE_PHONE_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/phone.png",
    INVOICE_RUPEE_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/rupee.png",
    INVOICE_VALOGO_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/VAlogo.png",
    INVOICE_VICON_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/VIcon.png",
    INVOICE_WEB_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/web.png",
    INVOICE_REGULAR_FONT: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/GlacialIndifferenceRegular.otf",
    INVOICE_BOLD_FONT: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/GlacialIndifferenceBold.otf",
    INVOICE_VALOGO_JPG_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/VAlogo.jpg",
    INVOICE_VICON_JPG_IMAGE: process.env.BASE_URL + "VV-LMS-SERVICE-COURSE-QUERY/getcontent/local/invoice_assets/VIcon.jpg",
};